import Head from 'next/head'
import Image from 'next/image'
import dynamic from 'next/dynamic'
import styles from '../styles/Home.module.css'
// import Hello from './component/Hello'

// dynamic rendering
const Hello = dynamic(() => (import('./component/Hello')));
const status = true;
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {/* <img src="/img.jpeg" alt="img"></img>
          <img src="/img2.jpeg" alt="img"></img> */}
          {/* <Image src="/img.jpeg" alt="img" width="3500" height="4000"></Image>
          <Image src="/img2.jpeg" alt="img" width="3500" height="4000"></Image> */}
          {status ? <Hello></Hello> : null}
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
